### PR TITLE
Invalid json body will now return 400 instead of 500 (#147)

### PR DESCRIPTION
**Pull request by joekienzle**

### CODE REVIEW

**Comment by joekienzle** [comment]
Please review @remmeier

**Comment by joekienzle** [comment]
@remmeier We need this bug fixed in our project. Could you please review it?

**Comment by remmeier** [comment]
will come to it today :-)

**Comment by remmeier** [comment]
looks great, thx

**Comment by remmeier** [comment]
release to follow today

**Comment by joekienzle** [comment]
Sweet thank you

**Comment by remmeier** [comment]
2.3.20171118162238

**Pull request merged**
