### PR TITLE
Order of attributes are not honored

### PR DESCRIPTION
**Pull request by erjaimin**
https://github.com/crnk-project/crnk-framework/issues/715

### CODE REVIEW

**Comment by remmeier** [comment]
looks good, in case you have time, can you add a little test to DocumentMapperTest? Just to ensure that this is working and stays like that.

**Comment by remmeier** [comment]
otherwise I should find some time.

**Comment by erjaimin** [comment]
Added a unit test

**Comment by remmeier** [comment]
perfect, thank you very much!

**Pull request merged**
