### PR TITLE
WIP: [238] Support versioning trough content type

### PR DESCRIPTION
**Pull request by michalgce**
Looks like it works but for sure code needs improvements, would be cool if you could place some feedback.

Knows missing things:
- [ ] Tests not passing for external modules
- [ ] Validation of adding versioned resources (overlaps)

Related to #238

### CODE REVIEW

**Comment by remmeier** [comment]
A great start!. A first iteration:

- the Version annotation could be moved to the other annotations like JsonApiResource and share the JsonApi prefix.
- Currently undecided whether not to move the versioning information from ResourceRepositoryInformation to ResourceInformation. The current one is more flexible (different repository implementations but with the same resource structure are possible), while for ResourceInformation the resource itself must change to create a new version since it would be tied to the resource. The later would allow CrnkClient to work with the version annotation  and send the proper version headers. Have to think about that.
- The difficult part: Those ResourceRegistry.getEntry(...)/hasEntry(...) methods are used everywhere. So any change here has a gigantic impact. Maybe we should introduce a new method "ResourceRegistry getXy(QueryContext)" that returns something similar to ResourceRegistry but scoped to the current request and then can be used just like the ResourceRegistry. For this to work, QueryContext could be complemented by a new attribute "version" based on the transmitted header.  That new object no longer need any versioning information, since it is request-specific.  Most methods of the ResourceRegistry could then be phased out/deprecated or rather for the time being delegate to a current properly scoped object (there is a thread local to get to QueryContext, but works only for the sync crnk version, not async). For a start this delegation would allow to have full versioning support in sync repositories without breaking/changing any API.  The desigsn would also allow more flexiblity in the future about those matters since it is not tied to versioning and can be used for any kind of request-specific behavior. Already now it would also easy url access since all those methods already carry a QueryContext parameter that could then be eliminated on the scoped object.

**Comment by makepanic** [comment]
Is there a specific reason why it was chosen to version the api by modifying/parsing the request `content-type` header?

There was a [long thread](https://github.com/json-api/json-api/issues/406) in the json-api issues around versioning and many different reasons pro/contra various approaches.

There are also approaches, [like stripe](https://stripe.com/blog/api-versioning), which completely hides the API version in some cases:

* A Stripe-Version header if one was supplied.
* The version of an authorized OAuth application if the request is made on the user’s behalf.
* The user’s pinned version, which is set on their very first request to Stripe.

I'm not that fluent with the crnk code but here are various questions I got when looking at the PR:

* is this pluggable so one could potentially reconfigure it to use a different pattern/approach?
* it looks like the header is only handled for usage in `Content-Type`, does this means this change won't effect api consumers as they would be using the `Accept` header?

I could also be completely wrong in how I understood the PR, so please excuse anything that's factual wrong 😅

**Comment by remmeier** [comment]
in general the PR is the early stages, not sure how much time @michalgce has. Major challenge is more in the backend implementation. How the "current" version is read from the request headers in that regard is a minor issue and could very well be made puggable. For the request header, it could/should go into the accept header, but with other possiblities pluggable I guess.

Major issue that has to be addressed in the PR is how to make that version transparently available through all places in the crnk enginem, in particular the resource registry as the resource registry now depends on the requested version.

**Comment by makepanic** [comment]
Thanks for the detailed explanation. You can ignore my previous comment then.

**Comment by remmeier** [comment]
closed due to inactivity, feel free to reopen

**Pull request closed without merging**
