### PR TITLE
throw ResourceNotFoundException

### LINKED ISSUE #19: findOne is not returning 404 when entity does not exist
from @phuo1032:

This issue seemed to be fixed at some point from a PR

#272

But the latest version does not have this change any more.
https://github.com/katharsis-project/katharsis-framework/blob/master/katharsis-core/src/main/java/io/katharsis/core/internal/dispatcher/controller/ResourceGet.java

The test case that verifies the NOT_FOUND status is also not there.
https://github.com/katharsis-project/katharsis-framework/blob/master/katharsis-core/src/test/java/io/katharsis/core/internal/dispatcher/controller/resource/ResourceGetTest.java

Is this a design change for restoring the previous behavior or am I suppose to throw the NOT_FOUND exception manually?

### PR DESCRIPTION
**Pull request by mohlek**
fix #19  

Todo:
- [x] Throw Exception when resource is `null`
- [x] Check for property
- [x] Add test

### CODE REVIEW

**Comment by remmeier** [comment]
the json api specification actually allows to return null in case of a missing record: see "404 Not Found" => http://jsonapi.org/format/. And so it is up to the repository to decide whether to throw an exception or null.

But agree that people many times want the 404. So maybe this commit could be complemented with a feature flag like CrnkProperties.RETURN_404_ON_NULL

**Comment by mohlek** [comment]
Yeah we should make it configurable. I'll change it.

**Comment by mohlek** [comment]
I added `PropertyProvider` to `ModuleRegistry` I thought this can be handy in many ways and allows me to get the property very easy

**Comment by mohlek** [comment]
@remmeier please take a look. Any suggestions?

**Pull request merged**
