### PR TITLE
Issue #263 resolution: merge conflict resolved

### PR DESCRIPTION
**Pull request by daniel-deluca**
To replace the previous Pull Request for issue #263

### CODE REVIEW

**Comment by daniel-deluca** [comment]
@remmeier : Done.

**Comment by remmeier** [comment]
perfect, thx!

**Comment by daniel-deluca** [comment]
Are you planning a release soon with that functionality ?

**Comment by daniel-deluca** [comment]
@remmeier When are you planning to have a new official release ?

**Comment by remmeier** [comment]
in progress, currently moving to bintray for publishing as I'm barely able to upload all packages to sonatype anymore.

**Pull request merged**
