### PR TITLE
Issue #263 solution

### PR DESCRIPTION
**Pull request by daniel-deluca**
@remmeier Based on your comment related to #263 (IN PR #256) I've refactored the code. Let me know if ok for the merge and release.
Apparently this is needed not just by me (based on comment in the Gitter Lobby)
Cheers

### CODE REVIEW

**Comment by remmeier** [comment]
merged the other one, so you can rebase here.

**Comment by remmeier** [comment]
on first look it looks good. one small catch: backwarts compatiblity must be maintained for everything not being internal (ResourceInformation and InformationBuilder). For the later I would assume resourceType == resourcePath by default if not specified otherwise. Will check in detail after the rebase. thx!

**Comment by remmeier** [comment]
I will try to get the reactive branch done the next two, three days do have a 2.6 release together

**Comment by daniel-deluca** [comment]
@remmeier : Backward compatibility: True, I completely forgot about this (too enthusiastic). I've fixed it  and pushed. Regarding resourcePath. If nothing is provided, the framework will use resourceType as resourcePath.

**Comment by daniel-deluca** [comment]
@remmeier : OK for the release time.

**Comment by remmeier** [comment]
can you do the the rebase? you should be able to take the most recent commits and put them on top of the current master branch. I will then check in detail.

**Comment by daniel-deluca** [comment]
I can't fix the conflict... rebase doesn't seem to solve anything

**Comment by remmeier** [comment]
maybe it is simplest to to just take out the resourcePath commit, then apply that on the master.

**Comment by daniel-deluca** [comment]
I've created another PR for this issue in order to solve the merge conflict.

**Pull request closed without merging**
